services:
  ai-match-service:
    environment:
      CONFIG_PROFILE: qa
  institute-service:
    environment:
      SPRING_PROFILES_ACTIVE: qa
  lecturer-service:
    environment:
      SPRING_PROFILES_ACTIVE: qa
  gatewayserver:
    environment:
      SPRING_PROFILES_ACTIVE: qa
