server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: institute-service
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:7080/realms/lecturelink}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:7080/realms/lecturelink/protocol/openid-connect/certs}
application:
  title: LectureLink
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka/}
info:
  app:
    name: institute-service
    description: LectureLink institutes, programs and subjects
    version: 1.0.0
